apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nginx
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hf-efs-sc
  nfs:
    path: /hf
    server: fs-03bd337a316af1cce.efs.ap-northeast-2.amazonaws.com

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-tomcat
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hf-efs-sc
  nfs:
    path: /hf
    server: fs-03bd337a316af1cce.efs.ap-northeast-2.amazonaws.com
